insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Coffee - Beans, Whole', 73.32);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Salmon - Fillets', 74.68);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Yogurt - Banana, 175 Gr', 46.34);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bar Energy Chocchip', 21.93);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Milk - Buttermilk', 42.57);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ice Cream - Fudge Bars', 34.87);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pork - Tenderloin, Fresh', 30.57);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Soup - Cream Of Broccoli', 53.51);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Pinot Grigio Collavini', 79.28);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chip - Potato Dill Pickle', 72.03);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Energy Drink - Redbull 355ml', 88.51);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Creme De Cacao Mcguines', 71.05);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Cava Aria Estate Brut', 6.47);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Rice - 7 Grain Blend', 57.55);
insert into product  (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ezy Change Mophandle', 10.87);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Sauce - Salsa', 35.98);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Glass - Wine, Plastic, Clear 5 Oz', 52.63);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Steampan - Half Size Shallow', 66.76);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Napkin White', 67.21);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cilantro / Coriander - Fresh', 31.73);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Cranberry, 341 Ml', 1.4);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Sole - Iqf', 81.86);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bread - Raisin Walnut Pull', 89.73);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Potatoes - Yukon Gold, 80 Ct', 77.47);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Toasted Head', 27.59);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Apple - Custard', 82.17);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Dc - Frozen Momji', 9.56);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chocolate - Sugar Free Semi Choc', 70.85);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Two Oceans Sauvignon', 41.23);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Carbonated Water - Lemon Lime', 33.71);
